name: sudoku_app
description: Ultra Premium Sudoku App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.4.9

  # Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Animations
  google_fonts: 6.1.0
  flutter_animate: ^4.3.0

  # Navigation
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
